services:
  humble-test:
    container_name: humble-test
    image: humble:cpu
    platform: linux/amd64
    privileged: true
    build:
      context: .
      dockerfile: Dockerfile.cpu
      args:
        - USER_NAME=${USER_NAME}
        - GROUP_NAME=${GROUP_NAME}
        - UID=${UID}
        - GID=${GID}
    environment:
      - DISPLAY=host.docker.internal:0
      - PULSE_SERVER=docker.for.mac.localhost
      - ROS_DOMAIN_ID=${ROS_DOMAIN_ID}
    ports:
      - "8888:8888"
      - "8080:8080" # Web VNC
      - "5901:5901" # VNC
    volumes:
       - /tmp/.X11-unix:/tmp/.X11-unix
       - $HOME/.Xauthority/:/root/.Xauthority
       - type: bind
         source: ~/.config/pulse
         target: /root/.config/pulse
       - /dev:/dev
    devices:
       - /dev:/dev
    ipc: host
    network_mode: host
    tty: true
    stdin_open: true
    user: "${UID}:${GID}"
    command: /bin/bash

  humble-test-gpu:
    container_name: humble-test-gpu
    image: humble:gpu
    privileged: true
    build:
      context: .
      dockerfile: Dockerfile.gpu
      args:
        - USER_NAME=${USER_NAME}
        - GROUP_NAME=${GROUP_NAME}
        - UID=${UID}
        - GID=${GID}
    environment:
      - DISPLAY=${DISPLAY}
      - XDG_RUNTIME_DIR=${XDG_RUNTIME_DIR}
      - PULSE_SERVER=docker.for.mac.localhost
      - ROS_DOMAIN_ID=${ROS_DOMAIN_ID}
    volumes:
       - /tmp/.X11-unix:/tmp/.X11-unix
       - $HOME/.Xauthority/:/root/.Xauthority
       - type: bind
         source: ~/.config/pulse
         target: /root/.config/pulse
       - /dev:/dev
    devices:
       - /dev:/dev
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    ipc: host
    network_mode: host
    tty: true
    stdin_open: true
    user: "${UID}:${GID}"
    command: /bin/bash -c "nvidia-smi"
